sudo: false
dist: trusty
language: java

install:
# Download and "install" jdk-9 from java.net
- cd ~
- wget http://download.java.net/java/jdk9/archive/174/binaries/jdk-9-ea+174_linux-x64_bin.tar.gz
- tar -xzf jdk-9-ea+174_linux-x64_bin.tar.gz
- export JAVA_HOME=$PWD/jdk-9
- PATH=$JAVA_HOME/bin:$PATH
- java -version
- cd $TRAVIS_BUILD_DIR

script:
- chmod u+x ./build.sh
- ./build.sh
- ./target/pro/bin/pro build test.pro
