sudo: false

language: java

before_install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

matrix:
  include:
# 9
    - jdk: oraclejdk9
      env: JDK_RELEASE='Oracle JDK 9'
      install: true
    - env: JDK_RELEASE='OpenJDK 9'
      install: . ./install-jdk.sh -F 9
# 10
    - env: oraclejdk10
      env: JDK_RELEASE='Oracle JDK 10'
      install: true
    - env: JDK_RELEASE='OpenJDK 10'
      install: . ./install-jdk.sh -F 10
# 11
    - env: JDK_RELEASE='Oracle JDK 11-ea'
      install: . ./install-jdk.sh -F 11 -L BCL
    - env: JDK_RELEASE='OpenJDK 11-ea'
      install: . ./install-jdk.sh -F 11 -L GPL
  allow_failures:
    - env: JDK_RELEASE='Oracle JDK 10'

script:
- java --version
- chmod u+x ./build.sh
- ./build.sh
- ./target/pro/bin/pro version
- ./target/pro/bin/pro build test.pro
