sudo: false
dist: trusty
language: java

install:
# Download and "install" jdk-9 from java.net
- wget http://download.java.net/java/jdk9/archive/170/binaries/jdk-9-ea+170_linux-x64_bin.tar.gz
- tar -xzf jdk-9-ea+170_linux-x64_bin.tar.gz
- export JAVA_HOME=$PWD/jdk-9
- PATH=$JAVA_HOME/bin:$PATH
- java -version

script:
- chmod u+x ./build.sh
- ./build.sh
- ./target/pro/bin/pro build test.pro
