sudo: false

language: java

matrix:
  include:
# 9
    - jdk: oraclejdk9
      env: JDK_RELEASE='OracleJDK 9'
      install: true
    - env: JDK_RELEASE='OpenJDK 9'
      install: . ./.travis/install-jdk.sh -F 9
# 10
    - env: JDK_RELEASE='OracleJDK 10-ea'
      install: . ./.travis/install-jdk.sh -F 10 -L BCL
    - env: JDK_RELEASE='OpenJDK 10-ea'
      install: . ./.travis/install-jdk.sh -F 10 -L GPL

script:
- java --version
- chmod u+x ./build.sh
- ./build.sh
- ./target/pro/bin/pro version
- ./target/pro/bin/pro build test.pro
