version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      # MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run
      - run: chmod u+x ./build.sh 
      - run: ./build.sh
      - run: ./target/pro/bin/pro version
      - run: ./target/pro/bin/pro build test.pro

