version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-ea-node-browsers
    working_directory: ~/repo
    environment:
      JAVA_HOME: ./jdk-11-lworld
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      
    steps:
      - checkout
      # install
      - run: |
          wget https://github.com/forax/valuetype-lambda/releases/download/8b2ca4fdb101/jdk-11-lworld.tar.gz
          tar zxvf jdk-11-lworld.tar.gz
          $JAVA_HOME/bin/java --version
          
      # build pro
      - run: chmod u+x ./build.sh
      - run: ./build.sh
      - run: sed -i.bak s/JLINK_VM_OPTIONS=/JLINK_VM_OPTIONS=-XX:+EnableValhalla/g ./target/pro/bin/pro
      - run: ./target/pro/bin/pro version
      - run: ./target/pro/bin/pro build test.pro
      - persist_to_workspace:
          root: target
          paths:
            - pro
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: target
      # package pro
      - run: |
          cd target
          zip -r ../pro-linux-early-access-lworld.zip pro
          cd ..
          
      # upload on github release
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.10.0/ghr_v0.10.0_linux_amd64.tar.gz
      - run: tar xvf ghr_v0.10.0_linux_amd64.tar.gz
      - run: mv ghr_v0.10.0_linux_amd64/ghr ghr
      - run: echo $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG
      - run: ./ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG pro-linux-early-access-lworld.zip
          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
