version: 2
jobs:
  build-lworld:
    docker:
      - image: circleci/openjdk:11-ea-node-browsers
    working_directory: ~/repo
    environment:
      JAVA_HOME: ./jdk-12-lworld
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      
    steps:
      - checkout
      # install
      - run: |
          wget https://github.com/forax/java-next/releases/download/untagged-8293aecc3c48178f8305/jdk-12-lworld.tar.gz
          tar zxvf jdk-12-lworld.tar.gz
          $JAVA_HOME/bin/java --version
          
      # build pro
      - run: chmod u+x ./build.sh
      - run: ./build.sh
      - run: sed -i.bak s/JLINK_VM_OPTIONS=/JLINK_VM_OPTIONS="\"-XX:+EnableValhalla\""/g ./target/pro/bin/pro
      - run: ./target/pro/bin/pro version
      - run: ./target/pro/bin/pro build test.pro
      - persist_to_workspace:
          root: target
          paths:
            - pro
  deploy-lworld:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: target
      # package pro
      - run: |
          cd target
          zip -r ../pro-linux-early-access-lworld.zip pro
          cd ..
          
      # upload on github release
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
      - run: tar xvf ghr_v0.12.0_linux_amd64.tar.gz
      - run: mv ghr_v0.12.0_linux_amd64/ghr ghr
      - run: echo $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG
      - run: ./ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG pro-linux-early-access-lworld.zip
  build-loom:
    docker:
      - image: circleci/openjdk:11-ea-node-browsers
    working_directory: ~/repo
    environment:
      JAVA_HOME: ./jdk-12-loom
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      
    steps:
      - checkout
      # install
      - run: |
          wget https://github.com/forax/java-next/releases/download/untagged-8293aecc3c48178f8305/jdk-12-loom.tar.gz
          tar zxvf jdk-12-loom.tar.gz
          $JAVA_HOME/bin/java --version
          
      # build pro
      - run: chmod u+x ./build.sh
      - run: ./build.sh
      - run: ./target/pro/bin/pro version
      - run: ./target/pro/bin/pro build test.pro
      - persist_to_workspace:
          root: target
          paths:
            - pro
  deploy-loom:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: target
      # package pro
      - run: |
          cd target
          zip -r ../pro-linux-early-access-loom.zip pro
          cd ..
          
      # upload on github release
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
      - run: tar xvf ghr_v0.12.0_linux_amd64.tar.gz
      - run: mv ghr_v0.12.0_linux_amd64/ghr ghr
      - run: echo $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG
      - run: ./ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG pro-linux-early-access-loom.zip    

  build-amber:
    docker:
      - image: circleci/openjdk:11-ea-node-browsers
    working_directory: ~/repo
    environment:
      JAVA_HOME: ./jdk-12-amber
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      
    steps:
      - checkout
      # install
      - run: |
          wget https://github.com/forax/java-next/releases/download/untagged-8293aecc3c48178f8305/jdk-12-amber.tar.gz
          tar zxvf jdk-12-amber.tar.gz
          $JAVA_HOME/bin/java --version
          
      # build pro
      - run: chmod u+x ./build.sh
      - run: ./build.sh
      - run: sed -i.bak s/JLINK_VM_OPTIONS=/JLINK_VM_OPTIONS="\"--enable-preview\""/g ./target/pro/bin/pro
      - run: ./target/pro/bin/pro version
      - run: ./target/pro/bin/pro build test.pro
      - persist_to_workspace:
          root: target
          paths:
            - pro
  deploy-amber:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: target
      # package pro
      - run: |
          cd target
          zip -r ../pro-linux-early-access-amber.zip pro
          cd ..
          
      # upload on github release
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
      - run: tar xvf ghr_v0.12.0_linux_amd64.tar.gz
      - run: mv ghr_v0.12.0_linux_amd64/ghr ghr
      - run: echo $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG
      - run: ./ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG pro-linux-early-access-amber.zip  
              
workflows:
  version: 2
  build-and-deploy-lworld:
    jobs:
      - build-lworld:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy-lworld:
          requires:
            - build-lworld
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

  build-and-deploy-loom:
    jobs:
      - build-loom:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy-loom:
          requires:
            - build-loom
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

  build-and-deploy-amber:
    jobs:
      - build-amber:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy-amber:
          requires:
            - build-amber
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
 