version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      # MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run
      - run: wget https://github.com/forax/java-next/releases/download/untagged-7c3c86a81f6e2e921c04/jdk-13-loom-linux.tar.gz
      - run: tar zxvf jdk-13-loom-linux.tar.gz
      - run: export JAVA_HOME=jdk-13-loom
      - run: export PATH=$JAVA_HOME/bin:$PATH
      - run: chmod u+x ./build.sh
      - run: ./build.sh
      - run: ./target/pro/bin/pro version
      - run: ./target/pro/bin/pro build test.pro

