version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      # MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # run
      - run:
          - chmod u+x ./build.sh
          - ./build.sh
          - ./target/pro/bin/pro version
          - ./target/pro/bin/pro build test.pro

